Feature/add colors
iamcodemaker/console_log pull request #6
Opened 2020-04-20 02:20 UTC by azriel91

Adds the ability to render log messages with colors.

The styling code is largely from [limira-rs/wasm-logger](https://gitlab.com/limira-rs/wasm-logger), though I cleaned it up a bit. I've put it behind a `"color"` feature flag and it is off by default.

What it looks like:

![log_messages_styled](https://user-images.githubusercontent.com/2993230/79707700-7216c900-8311-11ea-938d-a36b1a6eb278.png)

---

Between `console_log` and `wasm-logger`, I decided to submit the PR here since this already integrates with `fern`.

2020-04-20 20:47 UTC, iamcodemaker requested changes
Thanks for submitting a PR. Looks good. Just a few documentation/visibility related changes and this should be good to go.

2020-04-20 20:47 UTC, iamcodemaker commented on src/lib.rs
> +mod style;
Add `#[doc(hidden)]` here. The style stuff isn't relevant to external users.

2020-04-20 20:47 UTC, iamcodemaker commented on src/style.rs
> +pub struct Style<'s> {
If I'm not mistaken, this can be `pub(crate)`.

2020-04-20 21:07 UTC, azriel91 commented
Oh yeaps, good points! (eagle eye for that detail)

2020-04-21 05:14 UTC, iamcodemaker approved these changes

2020-04-21 05:15 UTC, merged

2020-04-21 05:43 UTC, iamcodemaker commented
Version `0.2.0` has been published with this change.